learning_rate: 0.001
gamma: 0.99
epsilon: 1.0
epsilon_decay: 0.995
epsilon_min: 0.01
replay_buffer_capacity: 50000
batch_size: 64
max_steps: 200000
target_update_frequency: 100  # Update target network every 100 episodes